### ISSUE TITLE
Use of `const`

### ISSUE THREAD

**Issue by TheCaptainCraken** [themarcman314/ftwgPassMan#4]
In C `const` is just a keyword that means a variable is read- only. **It does not mean that the value can not change**. Also it may prevent some optimizations from the compiler. For this reasons, it is considered better practice to use the `#define` directive instead:
```C
#define UPPERCASE_OFFSET 0x41
#define NUM_OF_LETTERS_IN_ALPHABET 26
#define LOWERCASE_OFFSET 0x61
#define NUMBERS_OFFSET 0x30
#define SPECIAL_OFFSET 0x20
```

**Comment by themarcman314** [comment]
fixed
