### ISSUE TITLE
Multiple types of characters

### ISSUE THREAD

**Issue by TheCaptainCraken** [themarcman314/ftwgPassMan#8]
Add functionality to make a password with multiple types of characters. E.g. `Pssw0rd123!`﻿

**Comment by themarcman314** [comment]
Yep I'm intending to do that, I've hinted to it in the README

**Comment by themarcman314** [comment]
Should we make it equally probable to have different types of characters meaning have as many characters of each type for a very long password?
Or should we make every character equally probable regardless of it's type (there would be few numbers and mostly letters and special characters).

**Comment by TheCaptainCraken** [comment]
I think the first but the second is good anyway

**Comment by themarcman314** [comment]
Works bitch
