### ISSUE TITLE
Usless brackets

### ISSUE THREAD

**Issue by TheCaptainCraken** [themarcman314/ftwgPassMan#9]
Why is there a pair of curly brackets wrapping the default case?

https://github.com/themarcman314/ftwgPassMan/blob/5b9e9dad9756a1f648a9851b8edd409a7f359748/src/main.c#L57-L76C5

**Comment by themarcman314** [comment]
They are not useless, you cannot declare the variable if it is not in a scope lol. I had that at the start but my lsp kept screaming at me.
https://stackoverflow.com/questions/92396/why-cant-variables-be-declared-in-a-switch-statement
